OUTER_SET golem = IDS_OF_SYMBOL(race GOLEM)
COPY_EXISTING_REGEXP ~^.+\.cre$~ ~override~
  READ_BYTE 0x272 race
  PATCH_IF race = golem BEGIN
    LPF DELETE_EFFECT INT_VAR match_opcode = 292 END
  END
BUT_ONLY


ACTION_IF GAME_IS ~bg2ee eet~ BEGIN

  COPY_EXISTING ~goliro.itm~   ~override~ // golems
                ~cdgoliro.itm~ ~override~
                ~golfle.itm~   ~override~
                ~irongol.itm~  ~override~
                ~golcla.itm~   ~override~
                ~golmag01.itm~ ~override~
                ~golsto.itm~   ~override~
                ~golstone.itm~ ~override~
                ~goltome4.itm~ ~override~
                ~golbra.itm~   ~override~
                ~ohbgol01.itm~ ~override~
    LPF DELETE_EFFECT INT_VAR match_opcode = 292 END
  BUT_ONLY

END
