OUTER_SET humanoid = IDS_OF_SYMBOL(general HUMANOID)

ACTION_IF GAME_IS ~bg2ee eet~ BEGIN

    COPY_EXISTING_REGEXP ~^.+\.cre$~ ~override~
        READ_BYTE 0x271 cre_general
        PATCH_IF cre_general = humanoid
            AND NOT "%SOURCE_RES%" STR_EQ "sendai"  
            AND NOT "%SOURCE_RES%" STR_EQ "sendai2" 
            AND NOT "%SOURCE_RES%" STR_EQ "sendai3" 
            AND NOT "%SOURCE_RES%" STR_EQ "sendai4" 
            AND NOT "%SOURCE_RES%" STR_EQ "sendai5" 
            AND NOT "%SOURCE_RES%" STR_EQ "sendai6" 
            AND NOT "%SOURCE_RES%" STR_EQ "sendai7" 
            AND NOT "%SOURCE_RES%" STR_EQ "sendai8" 
            AND NOT "%SOURCE_RES%" STR_EQ "balth"   
            AND NOT "%SOURCE_RES%" STR_EQ "cutbalth"
            AND NOT "%SOURCE_RES%" STR_EQ "gromnir" 
            AND NOT "%SOURCE_RES%" STR_EQ "finmel01"
            AND NOT "%SOURCE_RES%" STR_EQ "cutmelis"
            AND NOT "%SOURCE_RES%" STR_EQ "mel01"   
            AND NOT "%SOURCE_RES%" STR_EQ "meliss01"
            AND NOT "%SOURCE_RES%" STR_EQ "ohb4mlsn"
        BEGIN
          LPF DELETE_EFFECT INT_VAR match_opcode = 292 END
        END
    BUT_ONLY

END ELSE BEGIN

    COPY_EXISTING_REGEXP ~^.+\.cre$~ ~override~
        READ_BYTE 0x271 cre_general
        PATCH_IF cre_general = humanoid BEGIN
          LPF DELETE_EFFECT INT_VAR match_opcode = 292 END
        END
    BUT_ONLY

END
