COPY_EXISTING "finmel01.cre" ~override~
              "cutmelis.cre" ~override~
              "mel01.cre"    ~override~
              "meliss01.cre" ~override~
              "ohb4mlsn.cre" ~override~
              "balth.cre"    ~override~
              "cutbalth.cre" ~override~
              "sendai.cre"   ~override~
              "sendai2.cre"  ~override~
              "sendai3.cre"  ~override~
              "sendai4.cre"  ~override~
              "sendai5.cre"  ~override~
              "sendai6.cre"  ~override~
              "sendai7.cre"  ~override~
              "sendai8.cre"  ~override~
              "gromnir.cre"  ~override~
  LPF DELETE_EFFECT INT_VAR match_opcode = 292 END
