OUTER_SET planatar = IDS_OF_SYMBOL(race PLANATAR)
OUTER_SET darkplanatar = IDS_OF_SYMBOL(race DARKPLANATAR)
OUTER_SET solar = IDS_OF_SYMBOL(race SOLAR)
OUTER_SET antisolar = IDS_OF_SYMBOL(race ANTISOLAR)

COPY_EXISTING_REGEXP ~^.+\.cre$~ ~override~
  READ_BYTE 0x272 race
  PATCH_IF race = planatar OR race = darkplanatar OR race = solar OR race = antisolar BEGIN
    LPF DELETE_EFFECT INT_VAR match_opcode = 292 END
  END
BUT_ONLY
