DEFINE_PATCH_MACRO CRE_OP_PRESENT
BEGIN
    SET found_detection = "-1"
    READ_LONG 0x2c4 eff_offset
    READ_LONG 0x2c8 eff_length
    READ_BYTE 0x33 eff_type
    PATCH_IF eff_type = 0 BEGIN
        SET effect_size = 0x30
    END ELSE BEGIN
        SET effect_size = 0x108
    END
    SET found = 0
    FOR ( index = 0; index < eff_length; ++index ) BEGIN
        PATCH_IF eff_type = 0 BEGIN
            READ_SHORT eff_offset op
        END ELSE BEGIN
            READ_LONG (eff_offset + 0x08) op
        END
        PATCH_IF op = opcode BEGIN
            found = 1
            index = eff_length // break
        END
        eff_offset += effect_size
    END
    result = found
END

OUTER_SET opcode = 193
COPY_EXISTING_REGEXP ~^.+\.cre$~ ~override~
    LPM CRE_OP_PRESENT
    PATCH_IF found_detection BEGIN
        LPF DELETE_EFFECT INT_VAR match_opcode = 292 END
        LPF ADD_CRE_EFFECT INT_VAR opcode = 292 timing = 9 parameter1 = 1 END
    END
BUT_ONLY
