OUTER_SET mist = IDS_OF_SYMBOL(race MIST)
OUTER_SET shadow = IDS_OF_SYMBOL(race SHADOW)
OUTER_SET spectral_undead = IDS_OF_SYMBOL(race SPECTRAL_UNDEAD)
OUTER_SET wraith = IDS_OF_SYMBOL(race WRAITH)
OUTER_SET spectre = IDS_OF_SYMBOL(race SPECTRE)
OUTER_SET spectral_troll = IDS_OF_SYMBOL(class SPECTRAL_TROLL)
OUTER_SET undead = IDS_OF_SYMBOL(general UNDEAD)

COPY_EXISTING_REGEXP ~^.+\.cre$~ ~override~
    READ_BYTE 0x271 general
    READ_BYTE 0x272 race
    READ_BYTE 0x273 class

    PATCH_IF (race = mist AND general = undead)
        OR class = spectral_troll
        OR race = shadow
        OR race = spectral_undead
        OR race = wraith
        OR race = spectre
    BEGIN
        LPF DELETE_EFFECT INT_VAR match_opcode = 292 END
        LPF ADD_CRE_EFFECT INT_VAR opcode = 292 timing = 9 parameter1 = 1 END
    END

BUT_ONLY
